services:

# ==========================================
#                Vault Config
# ==========================================

  # vault-server:
  #   image: hashicorp/vault:1.11.3
  #   container_name: vault-server
  #   restart: always
  #   # volumes:
  #   #  - ./agent-configs/server1-dc1.hcl:/consul/config/server1-dc1.hcl
  #   #  - ./certs/:/consul/config/certs/
  #   networks:
  #     - consul
  #   ports:
  #     - "8200:8200"
  #   command: "server -dev -dev-root-token-id=root"

# ==========================================
#                DC1 Config
# ==========================================

  consul-server1-dc1:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-server1-dc1
    restart: always
    volumes:
     - ./agent-configs/server1-dc1.hcl:/consul/config/server1-dc1.hcl
     - ./certs/:/consul/config/certs/
     - ./license:/consul/config/license
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

# --------------------------------
#         DC1 Gateways
# --------------------------------


# --------------------------------
#         DC1 Clients
# --------------------------------

  consul-client-dc1-alpha:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-client-dc1-alpha
    restart: always
    volumes:
     - ./agent-configs/client-dc1-alpha.hcl:/consul/config/client-dc1-alpha.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-dc1-josh-long.hcl:/consul/config/services-dc1-josh-long.hcl
     - ./configs/services-dc1-josh.hcl:/consul/config/services-dc1-josh.hcl
    networks:
      - consul
    command: "agent"

  consul-client-dc1-charlie-ap1:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-client-dc1-charlie-ap1
    restart: always
    volumes:
     - ./agent-configs/client-dc1-charlie-ap1.hcl:/consul/config/dc1-client-charlie-ap1.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-donkey-ap1.hcl:/consul/config/services-donkey-ap1.hcl
    networks:
      - consul
    command: "agent"

  consul-client-dc1-delta-ap2:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-client-dc1-delta-ap2
    restart: always
    volumes:
     - ./agent-configs/client-dc1-delta-ap2.hcl:/consul/config/client-dc1-delta-ap2.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-unicorn-ap2.hcl:/consul/config/services-unicorn-ap2.hcl
    networks:
      - consul
    command: "agent"

  consul-client-dc1-echo-proj1:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-client-dc1-echo-proj1
    restart: always
    volumes:
     - ./agent-configs/client-dc1-echo-proj1.hcl:/consul/config/client-dc1-echo-proj1.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-dc1-proj1-baphomet.hcl:/consul/config/services-dc1-proj1-baphomet.hcl
    networks:
      - consul
    command: "agent"


  # ==========================================
  #                DC2 Config
  # ==========================================

  consul-server1-dc2:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-server1-dc2
    restart: always
    volumes:
     - ./agent-configs/server1-dc2.hcl:/consul/config/server1-dc2.hcl
     - ./certs/:/consul/config/certs/
     - ./license:/consul/config/license
    networks:
      - consul
    ports:
      - "8501:8500"
    command: "agent -bootstrap-expect=1"

# --------------------------------
#         DC1 Gateways
# --------------------------------


# --------------------------------
#         DC1 Clients
# --------------------------------

  consul-client-dc2-bravo:
    image: hashicorp/consul-enterprise:1.14.0-ent
    container_name: consul-client-dc2-bravo
    restart: always
    volumes:
     - ./agent-configs/client-dc2-bravo.hcl:/consul/config/client-dc2-bravo.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-dc2-josh.hcl:/consul/config/services-dc2-josh.hcl
    networks:
      - consul
    command: "agent"

# ==========================================
#             Network Config
# ==========================================

networks:
  consul:
    driver: bridge