services:

# ==========================================
#                Vault Config
# ==========================================

  # vault-server:
  #   image: hashicorp/vault:1.11.3
  #   container_name: vault-server
  #   restart: always
  #   # volumes:
  #   #  - ./agent-configs/server1-dc1.hcl:/consul/config/server1-dc1.hcl
  #   #  - ./certs/:/consul/config/certs/
  #   networks:
  #     - consul
  #   ports:
  #     - "8200:8200"
  #   command: "server -dev -dev-root-token-id=root"

# ==========================================
#                DC1 Config
# ==========================================

  consul-server1-dc1:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-server1-dc1
    restart: always
    volumes:
     - ./agent-configs/server1-dc1.hcl:/consul/config/server1-dc1.hcl
     - ./certs/:/consul/config/certs/
     - ./license:/consul/config/license
    networks:
      dc1:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"
    privileged: true

# --------------------------------
#         DC1 Gateways
# --------------------------------

  gateway-dc1:
    image: joshwolfer/consul-envoy:v1.14.1-ent_v1.24.0
    container_name: gateway-dc1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500   # Address of consul-server1-dc1
      CONSUL_GRPC_ADDR: 10.5.0.2:8502   # Address of consul-server1-dc1
      CONSUL_LICENSE_PATH: "/consul/config/license"
      CONSUL_CACERT: "/consul/config/certs/consul-agent-ca.pem"
      CONSUL_HTTP_TOKEN: "root"
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-service", "dc1-mgw",
      "-partition=default",
      "-address", "10.5.0.5:443",
      "-wan-address", "192.169.7.3:443" ]
      # "--",
      # "-l", "debug"]
    volumes:
      - ./license:/consul/config/license
      - ./certs/:/consul/config/certs/
    networks:
      dc1:
        ipv4_address: 10.5.0.5
      wan:
        ipv4_address: 192.169.7.3

# --------------------------------
#         DC1 Clients
# --------------------------------

# (Partition: default)
  consul-client-dc1-alpha:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-client-dc1-alpha
    restart: always
    volumes:
     - ./agent-configs/client-dc1-alpha.hcl:/consul/config/client-dc1-alpha.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-dc1-josh-long.hcl:/consul/config/services-dc1-josh-long.hcl
     - ./configs/services-dc1-josh.hcl:/consul/config/services-dc1-josh.hcl
    networks:
      dc1:
        ipv4_address: 10.5.0.10
    command: "agent"

# (Partition: donkey)
  consul-client-dc1-charlie-ap1:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-client-dc1-charlie-ap1
    restart: always
    volumes:
     - ./agent-configs/client-dc1-charlie-ap1.hcl:/consul/config/dc1-client-charlie-ap1.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-donkey-ap1.hcl:/consul/config/services-donkey-ap1.hcl
    networks:
      dc1:
        ipv4_address: 10.5.0.11
    command: "agent"

# (Partition: unicorn)
  consul-client-dc1-delta-ap2:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-client-dc1-delta-ap2
    restart: always
    volumes:
     - ./agent-configs/client-dc1-delta-ap2.hcl:/consul/config/client-dc1-delta-ap2.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-unicorn-ap2.hcl:/consul/config/services-unicorn-ap2.hcl
    networks:
      dc1:
        ipv4_address: 10.5.0.12
    command: "agent"

# (Partition: proj1)
  consul-client-dc1-echo-proj1:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-client-dc1-echo-proj1
    restart: always
    volumes:
     - ./agent-configs/client-dc1-echo-proj1.hcl:/consul/config/client-dc1-echo-proj1.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-dc1-proj1-baphomet.hcl:/consul/config/services-dc1-proj1-baphomet.hcl
    networks:
      dc1:
        ipv4_address: 10.5.0.13
    command: "agent"

# --------------------------------
#       DC1 Service Mesh
# --------------------------------

  # Service "Web" and Sidecar proxy
  # Eventually Put this in Proj2
  web:
    image: nicholasjackson/fake-service:v0.24.2
    container_name: web
    environment:
      NAME: Web (DC1)
      LISTEN_ADDR: 0.0.0.0:9090
      MESSAGE: "Hello World"
      SERVER_TYPE: "http"
      UPSTREAM_URIS: "http://localhost:9091,http://localhost:9092"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    networks:
      dc1:
        ipv4_address: 10.5.0.100
    ports:
      - 9000:9090
  web_envoy:
    image: joshwolfer/consul-envoy:v1.14.1-ent_v1.24.0
    container_name: web_envoy
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      CONSUL_LICENSE_PATH: "/consul/config/license"
      CONSUL_HTTP_TOKEN: "root"
      CONSUL_CACERT: "/consul/config/certs/consul-agent-ca.pem"
      SERVICE_CONFIG: /consul/config/services-dc1-web_v1.hcl
    volumes:
      - ./license:/consul/config/license
      - ./certs/:/consul/config/certs/
      - "./configs/services-dc1-web_v1.hcl:/consul/config/services-dc1-web_v1.hcl"
    command: ["consul", "connect", "envoy",
      "-sidecar-for", "web-v1",
      "-partition=default"]
    network_mode: "service:web"

  # Service "Web-upstream" and Sidecar proxy
  web-upstream:
    image: nicholasjackson/fake-service:v0.24.2
    container_name: web-upstream
    environment:
      NAME: Web Upstream (DC1)
      LISTEN_ADDR: 0.0.0.0:8000
      MESSAGE: "I am your upstream service. Yay."
      SERVER_TYPE: "http"
    networks:
      dc1:
        ipv4_address: 10.5.0.101
  web-upstream_envoy:
    image: joshwolfer/consul-envoy:v1.14.1-ent_v1.24.0
    container_name: web-upstream_envoy
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      CONSUL_LICENSE_PATH: "/consul/config/license"
      CONSUL_HTTP_TOKEN: "root"
      CONSUL_CACERT: "/consul/config/certs/consul-agent-ca.pem"
      SERVICE_CONFIG: /consul/config/services-dc1-web-upstream_v1.hcl
    volumes:
      - ./license:/consul/config/license
      - ./certs/:/consul/config/certs/
      - "./configs/services-dc1-web-upstream_v1.hcl:/consul/config/services-dc1-web-upstream_v1.hcl"
    command: ["consul", "connect", "envoy",
      "-sidecar-for", "web-upstream-v1",
      "-partition=default"]
    network_mode: "service:web-upstream"

  # ==========================================
  #                DC2 Config
  # ==========================================

  consul-server1-dc2:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-server1-dc2
    restart: always
    volumes:
     - ./agent-configs/server1-dc2.hcl:/consul/config/server1-dc2.hcl
     - ./certs/:/consul/config/certs/
     - ./license:/consul/config/license
    networks:
      dc2:
        ipv4_address: 10.6.0.2
      wan:
        ipv4_address: 192.169.7.4
    ports:
      - "8501:8500"
    command: "agent -bootstrap-expect=1"
    privileged: true

# --------------------------------
#         DC2 Gateways
# --------------------------------

  gateway-dc2:
    image: joshwolfer/consul-envoy:v1.14.1-ent_v1.24.0
    container_name: gateway-dc2
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.2:8500   # Address of consul-server1-dc2
      CONSUL_GRPC_ADDR: 10.6.0.2:8502   # Address of consul-server1-dc2
      CONSUL_LICENSE_PATH: "/consul/config/license"
      CONSUL_CACERT: "/consul/config/certs/consul-agent-ca.pem"
      CONSUL_HTTP_TOKEN: "root"
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-service", "dc2-mgw",
      "-partition=default",
      "-address", "10.6.0.5:443",
      "-wan-address", "192.169.7.5:443" ]
      # "--",
      # "-l", "debug"]
    volumes:
      - ./license:/consul/config/license
      - ./certs/:/consul/config/certs/
    networks:
      dc2:
        ipv4_address: 10.6.0.5
      wan:
        ipv4_address: 192.169.7.5

  gateway-dc2-chunky:
    image: joshwolfer/consul-envoy:v1.14.1-ent_v1.24.0
    container_name: gateway-dc2-chunky
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.11:8500   # Address of consul-server1-dc2
      CONSUL_GRPC_ADDR: 10.6.0.11:8502   # Address of consul-server1-dc2
      CONSUL_LICENSE_PATH: "/consul/config/license"
      CONSUL_CACERT: "/consul/config/certs/consul-agent-ca.pem"
      CONSUL_HTTP_TOKEN: "root"
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-service", "dc2-chunky-mgw",
      "-partition=chunky",
      "-address", "10.6.0.6:443",
      "-wan-address", "192.169.7.6:443" ]
      # "--",
      # "-l", "debug"]
    volumes:
      - ./license:/consul/config/license
      - ./certs/:/consul/config/certs/
    networks:
      dc2:
        ipv4_address: 10.6.0.6
      wan:
        ipv4_address: 192.169.7.6

# --------------------------------
#         DC2 Clients
# --------------------------------

# (Partition: default)
  consul-client-dc2-bravo:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-client-dc2-bravo
    restart: always
    volumes:
     - ./agent-configs/client-dc2-bravo.hcl:/consul/config/client-dc2-bravo.hcl
     - ./certs/:/consul/config/certs/
     - ./configs/services-dc2-josh.hcl:/consul/config/services-dc2-josh.hcl
    networks:
      dc2:
        ipv4_address: 10.6.0.10
    command: "agent"

# (Partition: chunky)
  consul-client-dc2-foxtrot:
    image: hashicorp/consul-enterprise:1.14.1-ent
    container_name: consul-client-dc2-foxtrot
    restart: always
    volumes:
     - ./agent-configs/client-dc2-foxtrot.hcl:/consul/config/client-dc2-foxtrot.hcl
     - ./certs/:/consul/config/certs/
    networks:
      dc2:
        ipv4_address: 10.6.0.11
    command: "agent"


# --------------------------------
#       DC2 Service Mesh
# --------------------------------

  # Service "Web-chunky" and Sidecar proxy
  web-chunky:
    image: nicholasjackson/fake-service:v0.24.2
    container_name: web-chunky
    environment:
      NAME: Web Chunky (DC2)
      LISTEN_ADDR: 0.0.0.0:8000
      MESSAGE: "I am Web Chunky!"
      SERVER_TYPE: "http"
    networks:
      dc2:
        ipv4_address: 10.6.0.100
  web-chunky_envoy:
    image: joshwolfer/consul-envoy:v1.14.1-ent_v1.24.0
    container_name: web-chunky_envoy
    environment:
      CONSUL_HTTP_ADDR: consul-client-dc2-foxtrot:8500
      CONSUL_GRPC_ADDR: consul-client-dc2-foxtrot:8502
      CONSUL_LICENSE_PATH: "/consul/config/license"
      CONSUL_HTTP_TOKEN: "root"
      CONSUL_CACERT: "/consul/config/certs/consul-agent-ca.pem"
      SERVICE_CONFIG: /consul/config/services-dc2-web-chunky_v1.hcl
    volumes:
      - ./license:/consul/config/license
      - ./certs/:/consul/config/certs/
      - ./configs/services-dc2-web-chunky_v1.hcl:/consul/config/services-dc2-web-chunky_v1.hcl
    command: ["consul", "connect", "envoy",
      "-sidecar-for", "web-chunky-v1",
      "-partition=chunky"]
    network_mode: "service:web-chunky"

  # ==========================================
  #              Network Config
  # ==========================================

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  dc2:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24


