apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: ice-cream
  namespace: banana-split
spec:
  splits:
    - weight: 34
      serviceSubset: vanilla
    - weight: 33
      serviceSubset: strawberry
    - weight: 33
      serviceSubset: chocolate