apiVersion: v1
kind: ServiceAccount
metadata:
  name: vanilla
  namespace: banana-split

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: vanilla
  namespace: banana-split
spec:
  protocol: http

---

apiVersion: v1
kind: Service
metadata:
  name: vanilla
  namespace: banana-split
  annotations:
    consul.hashicorp.com/service-sync: 'false'
spec:
  type: LoadBalancer
  selector:
    app: ice-cream
    version: vanilla
  ports:
    - name: ice-cream-port
      protocol: TCP
      port: 8991
      targetPort: 10000     # This should line up with the FakeService LISTEN_ADDR: 0.0.0.0:10000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla
  namespace: banana-split
  labels:
    app: ice-cream
    version: vanilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ice-cream
      version: vanilla
  template:
    metadata:
      labels:
        app: ice-cream
        version: vanilla
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        consul.hashicorp.com/service-tags: 'dc3-cernunnos'
        consul.hashicorp.com/service-meta-version: vanilla
    spec:
      serviceAccountName: vanilla
      containers:
        - name: ice-cream
          image: nicholasjackson/fake-service:v0.26.0
          ports:
            - containerPort: 10000
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:10000'
            - name: 'NAME'
              value: 'Vanilla Ice Cream (DC3 Cernunnos)'
            - name: 'MESSAGE'
              value: '<p><strong>The ice-cream Application</strong></p>'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'HTTP_CLIENT_REQUEST_TIMEOUT'
              value: '3s'