apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: example-https
  namespace: default
spec:
  destination:
    name: example-https
  sources:
    - name: externalz-alpha
      namespace: externalz
      action: allow